/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vvihYJn5P8U
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Signin() {
  return (
    <div className="flex min-h-[100dvh] flex-col items-center justify-center bg-gradient-to-br from-[#6c5ce7] to-[#a29bfe] px-4 py-12 sm:px-6 lg:px-8">
      <div className="w-full max-w-md space-y-8">
        <div>
          <Link href="#" className="flex justify-center" prefetch={false}>
            <MountainIcon className="h-12 w-12 text-white" />
            <span className="sr-only">Acme Inc</span>
          </Link>
          <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-white">Welcome back</h2>
          <p className="mt-2 text-center text-sm text-gray-300">
            Sign in to your account to connect with freelancers and employers.
          </p>
        </div>
        <form className="space-y-6" action="#" method="POST">
          <div>
            <Label htmlFor="email" className="sr-only">
              Email address
            </Label>
            <Input
              id="email"
              name="email"
              type="email"
              autoComplete="email"
              required
              className="relative block w-full appearance-none rounded-md border border-transparent bg-gray-100 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#a29bfe] focus:outline-none focus:ring-[#a29bfe] sm:text-sm"
              placeholder="Email address"
            />
          </div>
          <div>
            <Label htmlFor="password" className="sr-only">
              Password
            </Label>
            <Input
              id="password"
              name="password"
              type="password"
              autoComplete="current-password"
              required
              className="relative block w-full appearance-none rounded-md border border-transparent bg-gray-100 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#a29bfe] focus:outline-none focus:ring-[#a29bfe] sm:text-sm"
              placeholder="Password"
            />
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <input
                id="remember-me"
                name="remember-me"
                type="checkbox"
                className="h-4 w-4 rounded border-gray-300 text-[#a29bfe] focus:ring-[#a29bfe]"
              />
              <Label htmlFor="remember-me" className="ml-2 block text-sm text-gray-300">
                Remember me
              </Label>
            </div>
            <div className="text-sm">
              <Link href="#" className="font-medium text-[#a29bfe] hover:text-[#8a7ffc]" prefetch={false}>
                Forgot your password?
              </Link>
            </div>
          </div>
          <div>
            <Button
              type="submit"
              className="group relative flex w-full justify-center rounded-md border border-transparent bg-[#a29bfe] py-2 px-4 text-sm font-medium text-white hover:bg-[#8a7ffc] focus:outline-none focus:ring-2 focus:ring-[#a29bfe] focus:ring-offset-2"
            >
              Sign in
            </Button>
          </div>
        </form>
        <div className="text-center text-sm text-gray-300">
          Don't have an account?{" "}
          <Link href="#" className="font-medium text-[#a29bfe] hover:text-[#8a7ffc]" prefetch={false}>
            Sign up
          </Link>
        </div>
      </div>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
